apiVersion: v1
kind: Secret
metadata:
  name: consumer-secret
  namespace: consumer-ns
data:
  SPRING_RABBITMQ_USER: guest
  SPRING_RABBITMQ_PASS: guest
  SPRING_DATASOURCE_USER: sa
  SPRING_DATASOURCE_PASS: password
