apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  namespace: consumer-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: olumayor99/consumer-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: consumer-secret
            - configMapRef:
                name: consumer-config
