---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  namespace: app-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: olumayor99/consumer:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: consumer-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  namespace: app-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: olumayor99/producer:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: producer-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contract-deployment
  namespace: app-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contract
  template:
    metadata:
      labels:
        app: contract
    spec:
      containers:
        - name: contract
          image: olumayor99/contract:latest
          ports:
            - containerPort: 8080
