apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmqcluster-prod
spec:
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 0.5Gi
    limits:
      cpu: 500m
      memory: 0.5Gi
  rabbitmq:
    additionalConfig: |
      log.console.level = info
      channel_max = 1700
      default_user_tags.administrator = true
  service:
    type: ClusterIP
