name: Build and Push Docker Images to Repositories

on:
  push:
    branches: ["master"]
    paths:
      [
        "booking-consumer-service/**",
        "booking-producer-service/**",
        "booking-contract/**",
        ".github/workflows/build-and-push.yml",
      ]
  pull_request:
    branches: ["master"]
    paths:
      [
        "booking-consumer-service/**",
        "booking-producer-service/**",
        "booking-contract/**",
        ".github/workflows/build-and-push.yml",
      ]

jobs:
  build-and-push:
    name: Build Project and Push to Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Build Producer Docker image
        run: |
          cd booking-producer-service/
          docker build -t olumayor99/producer:latest .

      - name: Build Consumer Docker image
        run: |
          cd booking-consumer-service/
          docker build -t olumayor99/consumer:latest .

      - name: Build Contract Docker image
        run: |
          cd booking-contract/
          docker build -t olumayor99/contract:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push olumayor99/producer:latest
          docker push olumayor99/consumer:latest
          docker push olumayor99/contract:latest
