name: Build and Push Docker Images to Repositories

on:
  push:
    branches: ["master"]
    paths:
      [
        "booking-consumer-service/**",
        "booking-producer-service/**",
        "booking-contract/**",
        ".github/workflows/build-and-push.yml",
      ]
  pull_request:
    branches: ["master"]
    paths:
      [
        "booking-consumer-service/**",
        "booking-producer-service/**",
        "booking-contract/**",
        ".github/workflows/build-and-push.yml",
      ]
env:
  SPRING_RABBITMQ_HOST: ${{ secrets.SPRING_RABBITMQ_HOST }}
  SPRING_RABBITMQ_PORT: ${{ secrets.SPRING_RABBITMQ_PORT }}
  SPRING_RABBITMQ_USER: ${{ secrets.SPRING_RABBITMQ_USER }}
  SPRING_RABBITMQ_PASS: ${{ secrets.SPRING_RABBITMQ_PASS }}
  SPRING_LISTENER_DIRECT_DEFAULT: ${{ secrets.SPRING_LISTENER_DIRECT_DEFAULT }}
  SPRING_MAIN_ABDO: ${{ secrets.SPRING_MAIN_ABDO }}
  SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
  SPRING_DATASOURCE_DCN: ${{ secrets.SPRING_DATASOURCE_DCN }}
  SPRING_DATASOURCE_USER: ${{ secrets.SPRING_DATASOURCE_USER }}
  SPRING_DATASOURCE_PASS: ${{ secrets.SPRING_DATASOURCE_PASS }}
  SPRING_JPA_DATABASE_PLATFORM: ${{ secrets.SPRING_JPA_DATABASE_PLATFORM }}
  SPRING_JPA_HIBERNATE_DDL_AUTO: ${{ secrets.SPRING_JPA_HIBERNATE_DDL_AUTO }}
  SPRING_JPA_GENERATE_DDL: ${{ secrets.SPRING_JPA_GENERATE_DDL }}

jobs:
  build-and-push:
    name: Build Project and Push to Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Maven
        run: |
          mvn install -Dmaven.test.skip=true

      - name: Build Producer Docker image
        run: |
          cd booking-producer-service/
          docker build -t olumayor99/producer:latest .

      - name: Build Consumer Docker image
        run: |
          cd booking-consumer-service/
          docker build -t olumayor99/consumer:latest .

      - name: Build Contract Docker image
        run: |
          cd booking-contract/
          docker build -t olumayor99/contract:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push olumayor99/producer:latest
          docker push olumayor99/consumer:latest
          docker push olumayor99/contract:latest
