name: Build and Push Consumer Docker Image to Repository

on:
  #push:
   # branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  build-and-push:
    name: Build Project and Push to Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build Docker image
        env:
          FOO: '${{ secrets.FOO }}'
        run: |
          cd ../../../booking-consumer-service/
          docker build -t olumayor99/streamfinity-api:${{ steps.increment_version.outputs.version }} .
          docker tag olumayor99/streamfinity-api:${{ steps.increment_version.outputs.version }} olumayor99/streamfinity-api:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push olumayor99/streamfinity-api:${{ steps.increment_version.outputs.version }}
          docker push olumayor99/streamfinity-api:latest


