name: "Build & Deploy to EKS"

on:
  push:
    branches: ["master"]
    paths-ignore:
      [
        "booking-consumer-service/**",
        "booking-producer-service/**",
        "booking-contract/**",
        ".github/workflows/build-and-push.yml",
      ]
  pull_request:
    branches: ["master"]
    paths-ignore:
      [
        "booking-consumer-service/**",
        "booking-producer-service/**",
        "booking-contract/**",
        ".github/workflows/build-and-push.yml",
      ]

jobs:
  deploy:
    name: Deploy to EKS Cluster
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(<kubectl.sha256) kubectl" | sha256sum --check


          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Check AWS version
        run: |
          aws --version
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.EKS_REGION }}
          aws sts get-caller-identity

      - name: Connect to EKS cluster
        run: aws eks --region ${{ secrets.EKS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER }}

      - name: Install RabbitMQ Operator
        run: |
          kubectl apply -f "https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml"

      - name: Install RabbitMQ Cluster
        run: |
          helm repo add aws-ebs-csi-driver https://kubernetes-sigs.github.io/aws-ebs-csi-driver
          helm repo update
          helm upgrade --install aws-ebs-csi-driver \
              --namespace kube-system \
              aws-ebs-csi-driver/aws-ebs-csi-driver
          helm repo list
          helm repo update
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm dependency build
          export USERNAME='guest'
          export PASSWORD='guest'
          export ERLANG_COOKIE='guest'
          helm dependency build
          helm upgrade --install rabbitmq --namespace rabbitmq --create-namespace ./ -f values.yaml \
              --set podManagementPolicy=Parallel \
              --set replicaCount=3 \
              --set auth.username=${USERNAME} \
              --set auth.password=${PASSWORD} \
              --set auth.erlangCookie=${ERLANG_COOKIE} \
              --set metrics.enabled=true \
              --set persistence.size=10Gi \
              --set persistence.enabled=true \
              --set image.tag=3.10.13

      - name: Verify the deployment
        run: kubectl get pods -A
